### PR TITLE
Remove duplicate attributes in Other Transaction

### LINKED ISSUE #495: (FunctionClauseError) NewRelic.Transaction.Complete.transform_time_attrs/1
**Describe the bug**
Getting an error:

`(FunctionClauseError) no function clause matching in NewRelic.Transaction.Complete.transform_time_attrs/1`

**Environment**
* Elixir & Erlang version (`elixir -v`): 1.15.7, OTP 26.2.3
* Agent version (`mix deps | grep new_relic_agent`): 1.31.1

```
(FunctionClauseError) no function clause matching in NewRelic.Transaction.Complete.transform_time_attrs/1
(new_relic_agent 1.31.1) lib/new_relic/transaction/complete.ex:45: NewRelic.Transaction.Complete.transform_time_attrs(%{attributes: %{args: "[]", "absinthe.schema": "API.Schema.Customer", "absinthe.field_name": "featureSettings", "absinthe.instrumentation": "resolver_function", "absinthe.parent_type": "AccountStitchedFields", "absinthe.query_path": "account.featureSettings", "absinthe.type": "[FeatureSetting]"}, id: {["account", "featureSettings"], #Reference<0.2691711303.538705922.53875>}, pid: "#PID<0.113541.0>", start_time: 1738959170608354961, end_time_mono: -576459971158202036, start_time_mono: -576459971184069100, parent_id: :root, primary_name: "FeatureSettings.Schema.Customer.Resolvers.FeatureSetting.get", secondary_name: "API.Schema.Customer.account.featureSettings"})
(elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
(elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
(new_relic_agent 1.31.1) lib/new_relic/transaction/complete.ex:111: NewRelic.Transaction.Complete.extract_transaction_info/2
(new_relic_agent 1.31.1) lib/new_relic/transaction/complete.ex:17: NewRelic.Transaction.Complete.run/2
```

### PR DESCRIPTION
**Pull request by tpitale**

### CODE REVIEW

**Comment by tpitale** [comment]
Waiting for a PR build of my service to confirm this fix.

File: lib/new_relic/other_transaction.ex [hunk 1]
```diff
@@ -7,7 +7,7 @@ defmodule NewRelic.OtherTransaction do
 
     NewRelic.add_attributes(
       pid: inspect(self()),
-      start_time: System.system_time(),
+      system_time: System.system_time(),
```
Comment (binaryseed) [inline lib/new_relic/other_transaction.ex:10]: The call `Reporter.start_transaction(:other)` automatically adds `system_time` now actually...

We can remove both `start_time` and `start_time_mono` from this call here

Comment (binaryseed) [reply lib/new_relic/other_transaction.ex]: The code as-is isn't a bug but it is setting 2 un-necessary attributes which we could remove

**Review by binaryseed — APPROVED** [review]
